pollIntervalMs: 5000

lineageImporters:
  - className: observability.std.importer.lineage.MarquezLineageImporter
    params:
      baseUrl: "http://localhost:5000"
      depth: "20"

incidentDetectors:
  - className: observability.std.importer.detect.impls.UniqueValuesDetector
    params:
      connectionString: "jdbc:postgresql://localhost:15432/mydb?user=postgres"
      password: "secret"
      namespace: "postgres"
      tableName: "order"
      columnName: "status"
