pollIntervalMs: 5000

lineageImporters:
  - className: observability.std.importer.lineage.MarquezLineageImporter
    params:
      baseUrl: "http://marquez:5000"
      namespaces: "example1"
      depth: "20"

incidentDetectors:
  - className: observability.std.importer.detect.impls.UniqueValuesDetector
    params:
      connectionString: "jdbc:postgresql://postgres:5432/mydb?user=postgres"
      password: "secret"
      namespace: "default"
      tableName: "order"
      columnName: "id"
